import timeit
repetitions = 10000

dijSetup = """
from algorithms import dijkstra
dij = dijkstra.Graph(143)

dij.add_vertex_data(0,'Jurong East')
dij.add_vertex_data(1,'Bukit Batok')
dij.add_vertex_data(2,'Bukit Gombak')
dij.add_vertex_data(3,'Choa Chu Kang')
dij.add_vertex_data(4,'Yew Tee')
dij.add_vertex_data(5,'Kranji')
dij.add_vertex_data(6,'Marsiling')
dij.add_vertex_data(7,'Woodlands')
dij.add_vertex_data(8,'Admiralty')
dij.add_vertex_data(9,'Sembawang')
dij.add_vertex_data(10,'Canberra')
dij.add_vertex_data(11,'Yishun')
dij.add_vertex_data(12,'Khatib')
dij.add_vertex_data(13,'Yio Chu Kang')
dij.add_vertex_data(14,'Ang Mo Kio')
dij.add_vertex_data(15,'Bishan')
dij.add_vertex_data(16,'Braddell')
dij.add_vertex_data(17,'Toa Payoh')
dij.add_vertex_data(18,'Novena')
dij.add_vertex_data(19,'Newton')
dij.add_vertex_data(20,'Orchard')
dij.add_vertex_data(21,'Somerset')
dij.add_vertex_data(22,'Dhoby Ghaut')
dij.add_vertex_data(23,'City Hall')
dij.add_vertex_data(24,'Raffles Place')
dij.add_vertex_data(25,'Marina Bay')
dij.add_vertex_data(26,'Marina South Pier')
dij.add_vertex_data(27,'Pasir Ris')
dij.add_vertex_data(28,'Tampines')
dij.add_vertex_data(29,'Simei')
dij.add_vertex_data(30,'Tanah Merah')
dij.add_vertex_data(31,'Bedok')
dij.add_vertex_data(32,'Kembangan')
dij.add_vertex_data(33,'Eunos')
dij.add_vertex_data(34,'Paya Lebar')
dij.add_vertex_data(35,'Aljunied')
dij.add_vertex_data(36,'Kallang')
dij.add_vertex_data(37,'Lavender')
dij.add_vertex_data(38,'Bugis')
dij.add_vertex_data(39,'Tanjong Pagar')
dij.add_vertex_data(40,'Outram Park')
dij.add_vertex_data(41,'Tiong Bahru')
dij.add_vertex_data(42,'Redhill')
dij.add_vertex_data(43,'Queenstown')
dij.add_vertex_data(44,'Commonwealth')
dij.add_vertex_data(45,'Buona Vista')
dij.add_vertex_data(46,'Dover')
dij.add_vertex_data(47,'Clementi')
dij.add_vertex_data(48,'Chinese Garden')
dij.add_vertex_data(49,'Lakeside')
dij.add_vertex_data(50,'Boon Lay')
dij.add_vertex_data(51,'Pioneer')
dij.add_vertex_data(52,'Joo Koon')
dij.add_vertex_data(53,'Gul Circle')
dij.add_vertex_data(54,'Tuas Crescent')
dij.add_vertex_data(55,'Tuas West Road')
dij.add_vertex_data(56,'Tuas Link')
dij.add_vertex_data(57,'Expo')
dij.add_vertex_data(58,'Changi Airport')
dij.add_vertex_data(59,'HarbourFront')
dij.add_vertex_data(60,'Chinatown')
dij.add_vertex_data(61,'Clarke Quay')
dij.add_vertex_data(62,'Little India')
dij.add_vertex_data(63,'Farrer Park')
dij.add_vertex_data(64,'Boon Keng')
dij.add_vertex_data(65,'Potong Pasir')
dij.add_vertex_data(66,'Woodleigh')
dij.add_vertex_data(67,'Serangoon')
dij.add_vertex_data(68,'Kovan')
dij.add_vertex_data(69,'Hougang')
dij.add_vertex_data(70,'Buangkok')
dij.add_vertex_data(71,'Sengkang')
dij.add_vertex_data(72,'Punggol')
dij.add_vertex_data(73,'Punggol Coast')
dij.add_vertex_data(74,'Bras Basah')
dij.add_vertex_data(75,'Esplanade')
dij.add_vertex_data(76,'Promenade')
dij.add_vertex_data(77,'Nicoll Highway')
dij.add_vertex_data(78,'Stadium')
dij.add_vertex_data(79,'Mountbatten')
dij.add_vertex_data(80,'Dakota')
dij.add_vertex_data(81,'MacPherson')
dij.add_vertex_data(82,'Tai Seng')
dij.add_vertex_data(83,'Bartley')
dij.add_vertex_data(84,'Lorong Chuan')
dij.add_vertex_data(85,'Marymount')
dij.add_vertex_data(86,'Caldecott')
dij.add_vertex_data(87,'Botanic Gardens')
dij.add_vertex_data(88,'Farrer Road')
dij.add_vertex_data(89,'Holland Village')
dij.add_vertex_data(90,'one-north')
dij.add_vertex_data(91,'Kent Ridge')
dij.add_vertex_data(92,'Haw Par Villa')
dij.add_vertex_data(93,'Pasir Panjang')
dij.add_vertex_data(94,'Labrador Park')
dij.add_vertex_data(95,'Telok Blangah')
dij.add_vertex_data(96,'Bayfront')
dij.add_vertex_data(97,'Bukit Panjang')
dij.add_vertex_data(98,'Cashew')
dij.add_vertex_data(99,'Hillview')
dij.add_vertex_data(100,'Hume')
dij.add_vertex_data(101,'Beauty World')
dij.add_vertex_data(102,'King Albert Park')
dij.add_vertex_data(103,'Sixth Avenue')
dij.add_vertex_data(104,'Tan Kah Kee')
dij.add_vertex_data(105,'Stevens')
dij.add_vertex_data(106,'Rochor')
dij.add_vertex_data(107,'Downtown')
dij.add_vertex_data(108,'Telok Ayer')
dij.add_vertex_data(109,'Fort Canning')
dij.add_vertex_data(110,'Bencoolen')
dij.add_vertex_data(111,'Jalan Besar')
dij.add_vertex_data(112,'Bendemeer')
dij.add_vertex_data(113,'Geylang Bahru')
dij.add_vertex_data(114,'Mattar')
dij.add_vertex_data(115,'Ubi')
dij.add_vertex_data(116,'Kaki Bukit')
dij.add_vertex_data(117,'Bedok North')
dij.add_vertex_data(118,'Bedok Reservoir')
dij.add_vertex_data(119,'Tampines West')
dij.add_vertex_data(120,'Tampines East')
dij.add_vertex_data(121,'Upper Changi')
dij.add_vertex_data(122,'Woodlands North')
dij.add_vertex_data(123,'Woodlands South')
dij.add_vertex_data(124,'Springleaf')
dij.add_vertex_data(125,'Lentor')
dij.add_vertex_data(126,'Mayflower')
dij.add_vertex_data(127,'Bright Hill')
dij.add_vertex_data(128,'Upper Thomson')
dij.add_vertex_data(129,'Napier')
dij.add_vertex_data(130,'Orchard Boulevard')
dij.add_vertex_data(131,'Great World')
dij.add_vertex_data(132,'Havelock')
dij.add_vertex_data(133,'Maxwell')
dij.add_vertex_data(134,'Shenton Way')
dij.add_vertex_data(135,'Gardens by the Bay')
dij.add_vertex_data(136,'Tanjong Rhu')
dij.add_vertex_data(137,'Katong Park')
dij.add_vertex_data(138,'Tanjong Katong')
dij.add_vertex_data(139,'Marine Parade')
dij.add_vertex_data(140,'Marine Terrace')
dij.add_vertex_data(141,'Siglap')
dij.add_vertex_data(142,'Bayshore')


dij.add_edge(0, 1, 1)
dij.add_edge(0, 2, 2)
dij.add_edge(0, 4, 9)
dij.add_edge(1, 3, 5)
dij.add_edge(2, 3, 3)
dij.add_edge(3, 4, 2)
dij.add_edge(1, 4, 8)
dij.add_edge(0, 5, 2)
dij.add_edge(4, 5, 10)
dij.add_edge(3, 5, 2)
"""

bfSetup = """
from algorithms import bruteforce
bf = bruteforce.Graph(6)

bf.add_vertex_data(0, 'A')
bf.add_vertex_data(1, 'B')
bf.add_vertex_data(2, 'C')
bf.add_vertex_data(3, 'D')
bf.add_vertex_data(4, 'E')
bf.add_vertex_data(5, 'F')

bf.add_edge(0, 1, 1)
bf.add_edge(0, 2, 2)
bf.add_edge(0, 4, 9)
bf.add_edge(1, 3, 5)
bf.add_edge(2, 3, 3)
bf.add_edge(3, 4, 2)
bf.add_edge(1, 4, 8)
bf.add_edge(0, 5, 2)
bf.add_edge(4, 5, 10)
bf.add_edge(3, 5, 2)
"""

aSSetup = """
from algorithms import astar
aS = astar.Graph(6)

aS.add_vertex_data(0, 'A')
aS.add_vertex_data(1, 'B')
aS.add_vertex_data(2, 'C')
aS.add_vertex_data(3, 'D')
aS.add_vertex_data(4, 'E')
aS.add_vertex_data(5, 'F')

aS.add_edge(0, 1, 1)
aS.add_edge(0, 2, 2)
aS.add_edge(0, 4, 9)
aS.add_edge(1, 3, 5)
aS.add_edge(2, 3, 3)
aS.add_edge(3, 4, 2)
aS.add_edge(1, 4, 8)
aS.add_edge(0, 5, 2)
aS.add_edge(4, 5, 10)
aS.add_edge(3, 5, 2)
"""

bfFile = open("data/bf.txt", 'a')
dijFile = open("data/dij.txt", 'a')
aSFile = open("data/as.txt", 'a')

for x in range(0, 100):
    bfExec = timeit.timeit(stmt="print(bf.bruteforce('A'))", setup=bfSetup, number=repetitions) * 1000 / repetitions
    dijExec = timeit.timeit(stmt="print(dij.dijkstra('A'))", setup=dijSetup, number=repetitions) * 1000 / repetitions
    aSExec = timeit.timeit(stmt="print(aS.astar('A', 'E'))", setup=aSSetup, number=repetitions) * 1000 / repetitions

    bfExec = round(bfExec, 3)
    dijExec = round(dijExec, 3)
    aSExec = round(aSExec, 3)

    print(f"bfExec runtime: {bfExec}ms")
    print(f"dijExec runtime: {dijExec}ms")
    print(f"aSExec runtime: {aSExec}ms")

    bfFile.write(f"{bfExec:.3f}\n")
    dijFile.write(f"{dijExec:.3f}\n")
    aSFile.write(f"{aSExec:.3f}\n")